services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bazhov-api
    ports:
      - "${API_PORT}:3000"
    environment:
      PORT: ${API_PORT}

      SITE_URL: ${SITE_URL}
      API_KEY: ${API_KEY}

      STORAGE_PATH: "/app/${STORAGE_PATH}"

      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DB_TYPE: "postgresql"
    volumes:
      - storage:/app/${STORAGE_PATH}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: bazhov-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  storage:
